title: 10 Git Commands for Collaborating
author: Jim Tyhurst
subtitle: Learn Just Enough Git and GitHub to Contribute to an Open Source Project
abstract: This is a short tutorial to learn just enough Git and GitHub
    to contribute to an open source project with confidence. 
    I explain how you only need to learn 10 commands and a few
    workflows, in order to use Git to collaborate with others.
date:
- 2021-03-14
keywords: 
- Git
- GitHub
- open source
subject: Git 
description: This is a short tutorial to learn just enough Git and GitHub to contribute to an open source project with confidence. You only need to learn a few commands and a few workflows, in order to use Git to collaborate with others.
category: software development
papersize: letter
margin-left: 90pt
margin-right: 72pt
margin-top: 54pt
margin-bottom: 54pt
toccolor: blue
linkcolor: blue
urlcolor: blue
